export const products = [{
        id: 1,
        name: 'AllSaints Redact oversized',
        price: 'AED 2,050.00',
        image: '/images/product-1.png',
        hoverImage: '/images/product-1-1.jpg',
        descriptionText: 'Unveiled at the Spring-Summer 2025 Ready-to-Wear Fashion Show and a hallmark Dior silhouette, the blouse is reimagined an elegant and laid-back creation. Crafted in black cotton silhouette enhanced by an off-the-shoulder spread collar and adjustable straps with metal buckles. The blouse be paired Unveiled at the Spring-Summer 2025 Ready-to-Wear Fashion Show and a hallmark Dior silhouette, the blouse is reimagined an elegant and laid-back creation. Crafted in black cotton silhouette enhanced by an off-the-shoulder spread collar and adjustable straps with metal buckles. The blouse be paired ...',
        featuresText: 'The blouse features premium quality black cotton, an off-the-shoulder spread collar, and adjustable straps with stylish metal buckles. Designed for both comfort and elegance, making it perfect for various occasions. The blouse features premium quality black cotton, an off-the-shoulder spread collar, and adjustable straps with stylish metal buckles. Designed for both comfort and elegance, making it perfect for various occasions',
        images: [
            '/images/product-1.png',
            '/images/product2.png',
            '/images/product3.png',
            '/images/product4.png',
            '/images/product5.png',
        ],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['#ff0000', '#00aaff', '#32cd32', '#000000', '#800080'],
    },
    {
        id: 2,
        name: 'Camisole - 8110',
        price: 'Rs. 2,050.00',
        image: '/images/product-2.png',
        hoverImage: '/images/product-2-2.jpg',
        descriptionText: 'A versatile camisole perfect for any occasion, crafted with the highest quality materials. Its sleek design ensures a comfortable fit that pairs well with any outfit.',
        featuresText: 'This camisole is made from premium materials, featuring adjustable straps for a customizable fit. Its breathable fabric makes it ideal for warm weather.',
        images: [
            '/images/product-2.png',
            '/images/product2.png',
            '/images/product3.png',
            '/images/product4.png',
            '/images/product5.png',
        ],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['#ff0000', '#00aaff', '#32cd32', '#000000', '#800080'],
    },
    {
        id: 3,
        name: 'Helek Silk Shirt',
        price: 'Rs. 2,050.00',
        image: '/images/product-3.png',
        hoverImage: '/images/product-3-3.jpg',
        descriptionText: 'A luxurious silk shirt that speaks elegance and grace. Perfect for formal occasions or a night out.',
        featuresText: 'Crafted from 100% silk, this shirt features a relaxed fit and a classic collar. It is designed for ultimate comfort and sophistication.',
        images: [
            '/images/product-3.png',
            '/images/product2.png',
            '/images/product3.png',
            '/images/product4.png',
            '/images/product5.png',
        ],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['#ff0000', '#00aaff', '#32cd32', '#000000', '#800080'],
    },
    {
        id: 4,
        name: 'Long Sleeve Dropped',
        price: 'Rs. 2,050.00',
        image: '/images/product-4.png',
        hoverImage: '/images/product-4-4.jpg',
        descriptionText: 'A modern twist on a classic long sleeve, featuring a dropped shoulder design for added style.',
        featuresText: 'Made from a soft cotton blend, this shirt offers a relaxed fit with dropped shoulders for a contemporary look. Ideal for casual wear.',
        images: [
            '/images/product-4.png',
            '/images/product2.png',
            '/images/product3.png',
            '/images/product4.png',
            '/images/product5.png',
        ],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['#ff0000', '#00aaff', '#32cd32', '#000000', '#800080'],
    },
    {
        id: 5,
        name: 'Spliced Volume Shirt',
        price: 'Rs. 2,050.00',
        image: '/images/product-5.png',
        hoverImage: '/images/product-5-5.jpg',
        descriptionText: 'An eye-catching spliced design with added volume for a unique silhouette. Perfect for making a statement.',
        featuresText: 'This shirt features a spliced design with added volume in the sleeves. Its bold pattern is sure to turn heads.',
        images: [
            '/images/product-5.png',
            '/images/product2.png',
            '/images/product3.png',
            '/images/product4.png',
            '/images/product5.png',
        ],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['#ff0000', '#00aaff', '#32cd32', '#000000', '#800080'],
    },
    {
        id: 6,
        name: 'Spring Fern Floral Bikini Set',
        price: 'Rs. 2,050.00',
        image: '/images/product-6.png',
        hoverImage: '/images/product-6-6.jpg',
        descriptionText: 'A floral bikini set that captures the essence of spring, with vibrant patterns and comfortable fit.',
        featuresText: 'This bikini set features a floral print with adjustable straps for a perfect fit. Made from quick-drying materials ideal for the beach.',
        images: [
            '/images/product-6.png',
            '/images/product2.png',
            '/images/product3.png',
            '/images/product4.png',
            '/images/product5.png',
        ],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['#ff0000', '#00aaff', '#32cd32', '#000000', '#800080'],
    },
    {
        id: 7,
        name: 'One Piece Blue Nessy Spring',
        price: 'Rs. 2,050.00',
        image: '/images/product-7.png',
        hoverImage: '/images/product-7-7.jpg',
        descriptionText: 'A stylish one-piece swimsuit that combines comfort and elegance, perfect for the pool or beach.',
        featuresText: 'This one-piece features a flattering cut with a unique pattern. Its stretchy fabric ensures a snug fit.',
        images: [
            '/images/product-7.png',
            '/images/product2.png',
            '/images/product3.png',
            '/images/product4.png',
            '/images/product5.png',
        ],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['#ff0000', '#00aaff', '#32cd32', '#000000', '#800080'],
    },
    {
        id: 8,
        name: 'Oversized Shirt in Olive Stripe',
        price: 'Rs. 2,050.00',
        image: '/images/product-8.png',
        hoverImage: '/images/product-8-8.jpg',
        descriptionText: 'An oversized shirt with olive stripe patterns, offering a relaxed fit that is both comfortable and stylish.',
        featuresText: 'Made from a breathable fabric, this shirt features classic stripes and a loose fit, making it a versatile wardrobe staple.',
        images: [
            '/images/product-8.png',
            '/images/product2.png',
            '/images/product3.png',
            '/images/product4.png',
            '/images/product5.png',
        ],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['#ff0000', '#00aaff', '#32cd32', '#000000', '#800080'],
    },
    {
        id: 9,
        name: 'Oversized Shirt in Olive Stripe',
        price: 'Rs. 2,050.00',
        image: '/images/product-8.png',
        hoverImage: '/images/product-9-9.jpg',
        descriptionText: 'An oversized shirt with olive stripe patterns, offering a relaxed fit that is both comfortable and stylish.',
        featuresText: 'Made from a breathable fabric, this shirt features classic stripes and a loose fit, making it a versatile wardrobe staple.',
        images: [
            '/images/product-8.png',
            '/images/product2.png',
            '/images/product3.png',
            '/images/product4.png',
            '/images/product5.png',
        ],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['#ff0000', '#00aaff', '#32cd32', '#000000', '#800080'],
    },
    {
        id: 10,
        name: 'Oversized Shirt in Olive Stripe',
        price: 'Rs. 2,050.00',
        image: '/images/product-8.png',
        hoverImage: '/images/product-10-10.jpg',
        descriptionText: 'An oversized shirt with olive stripe patterns, offering a relaxed fit that is both comfortable and stylish.',
        featuresText: 'Made from a breathable fabric, this shirt features classic stripes and a loose fit, making it a versatile wardrobe staple.',
        images: [
            '/images/product-8.png',
            '/images/product2.png',
            '/images/product3.png',
            '/images/product4.png',
            '/images/product5.png',
        ],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['#ff0000', '#00aaff', '#32cd32', '#000000', '#800080'],
    },
    {
        id: 11,
        name: 'Oversized Shirt in Olive Stripe',
        price: 'Rs. 2,050.00',
        image: '/images/product-8.png',
        hoverImage: '/images/product-11-11.jpg',
        descriptionText: 'An oversized shirt with olive stripe patterns, offering a relaxed fit that is both comfortable and stylish.',
        featuresText: 'Made from a breathable fabric, this shirt features classic stripes and a loose fit, making it a versatile wardrobe staple.',
        images: [
            '/images/product-8.png',
            '/images/product2.png',
            '/images/product3.png',
            '/images/product4.png',
            '/images/product5.png',
        ],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['#ff0000', '#00aaff', '#32cd32', '#000000', '#800080'],
    },
    {
        id: 12,
        name: 'Oversized Shirt in Olive Stripe',
        price: 'Rs. 2,050.00',
        image: '/images/product-8.png',
        hoverImage: '/images/product-12-12.jpg',
        descriptionText: 'An oversized shirt with olive stripe patterns, offering a relaxed fit that is both comfortable and stylish.',
        featuresText: 'Made from a breathable fabric, this shirt features classic stripes and a loose fit, making it a versatile wardrobe staple.',
        images: [
            '/images/product-8.png',
            '/images/product2.png',
            '/images/product3.png',
            '/images/product4.png',
            '/images/product5.png',
        ],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['#ff0000', '#00aaff', '#32cd32', '#000000', '#800080'],
    },
    {
        id: 13,
        name: 'Oversized Shirt in Olive Stripe',
        price: 'Rs. 2,050.00',
        image: '/images/product-8.png',
        hoverImage: '/images/product-13-13.jpg',
        descriptionText: 'An oversized shirt with olive stripe patterns, offering a relaxed fit that is both comfortable and stylish.',
        featuresText: 'Made from a breathable fabric, this shirt features classic stripes and a loose fit, making it a versatile wardrobe staple.',
        images: [
            '/images/product-8.png',
            '/images/product2.png',
            '/images/product3.png',
            '/images/product4.png',
            '/images/product5.png',
        ],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['#ff0000', '#00aaff', '#32cd32', '#000000', '#800080'],
    },
];